### PR TITLE
Replace @babel/polyfill

### PR DESCRIPTION
**Pull request by brunoparga**
This should solve #11. I am gonna test this on my project that uses this package. I now feel the other PRs are redundant, I'm gonna close them and you can reopen them if need be. I'm looking forward to hearing from you on this proposal!

### CODE REVIEW

**Comment by brunoparga** [comment]
I am happy to report this works on my project.

**Comment by igoodwinTechtonic** [comment]
Hello, I'm interested in using this package for a personal project, but am wondering if this pull request will be merged to fix the issue with the deprecation of @babel/polyfill. 
Is there a possibility this package can be updated / the changes can be merged soon?

**Comment by brunoparga** [comment]
Hi @igoodwinTechtonic , since there's been no reply from @ankita1010 , I published my version as its own package, `@brunoparga/react-combine-reducers`. You just have to prepend the part with the @ sign on your package.json to use it.

**Comment by igoodwinTechtonic** [comment]
Thanks for the reply @brunoparga I'll check it out and let you know how it goes!

**Comment by ankita1010** [comment]
Hi @igoodwinTechtonic  @brunoparga 

I apologize extremely for not being able to respond on time. This PR looks great to me. If I have your approval, I will go ahead and merge it. What do you say?

**Comment by brunoparga** [comment]
Sounds great! I'm hindsight, it's probably better to squash all of these commits. The main branch on my repo has a squashed commit - so maybe merge that instead? Let me know how you want to proceed - just merging this PR works just as fine 😁

**Comment by ankita1010** [comment]
I could squash the commits and then merge the PR I guess 😁

**Comment by brunoparga** [comment]
Awesome! Once it's merged I'll unpublish my fork, it won't be necessary any
more. But I can only do it tomorrow. Thank you!

**Comment by ankita1010** [comment]
Thank you for showing interest in this repo. Means a lot.

**Comment by brunoparga** [comment]
I have deprecated my package (did I break some record for shortest-lived package ever? 🤔)

Have you published the new version to npm?

**Comment by igoodwinTechtonic** [comment]
Thanks for the update guys! However, the package on npm is waiting for your update @ankita1010 to the latest version.

**Comment by ankita1010** [comment]
Guys I'll be publishing it tomorrow, getting my laptop delivered after a repair 😃😅

**Comment by igoodwinTechtonic** [comment]
@ankita1010 Are you able to publish the updated package to npm today?

**Comment by ankita1010** [comment]
Yes. It is done. Might take a while to show on the website but if you install it should be the updated version.
@igoodwinTechtonic @brunoparga 
Thanks a lot.

**Pull request merged**
